### ISSUE TITLE
Tab indexing is not always properly working in Visual Editor's property editor

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#271]
As part of that issue we need to review all tab index mechanism in property editor and make appropriate fixes if needed.

**Comment by piotrzarzycki21** [comment]
Tab indexing in property editor has been fixed.

**Comment by atinprominic** [comment]
There is issue with below UI controls:

1. Input Mask: Not focusing on value property
2. TAB View: Only the properties -Width, Height and Scrollable are getting focus.
3. Fieldset: Direction, Horiz Align and Vert Align properties are not getting focus.
4. Data Table: Columns property not getting focus
5. Grid: Only Width and Height properties are getting focus

Apart from the above issues, the TAB key should work with Shift key as well. It will allow the user to navigate the properties in reverse order.

**Comment by JoelProminic** [comment]
InputMask and TabView seem find now.

Shift-Tab still does not work.

Are @atinprominic's updates relevant to the original issue?  I am not clear what the problem was on the original issue, so I'm not sure how to test it.

**Comment by piotrzarzycki21** [comment]
@atinprominic all focus problems has been fixed. I will raise separate issue for shift-tab support. Note that I omit intentionally focusing Grids and Lists in property editor. I'm not sure whether they have to be focused. There is some issue when I focus that element, so I'm leaving for now them unfocused.

**Comment by atinprominic** [comment]
@piotrzarzycki21 I tested and found that the issue I reported are fixed now.
