### ISSUE TITLE
"Permission Denied" Errors on Filesystem After Git Checkout

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#315]
While testing the GitHub integration (#295), I got some file permission errors when checking out a branch.  After some investigation, it seems that this is caused because Windows considered the files to be currently open by a different application:  https://community.atlassian.com/t5/Git-questions/Windows-permission-denied-on-switching-branches/qaq-p/407440

I ran a test, and I was able to trace the problem to the language server.  Here is my test procedure.  My test environment is Windows 10, version 1703, Java 1.8.0_161.

1. Open a project in Moonshine
2. Manually kill the language server
3. Checkout a different branch from the command line
4. Run "git status" - The output does not show any errors
5. Reopen the project in Moonshine - the language server starts again
6. Checkout a different branch from the command line
7. The language server reports errors
8. Run "git status".  The output shows file permission errors 
9. Close Moonshine
10. Run "git status" - The errors are cleared

Here is the output from the language server.  On futher review, it looks like just indicates that the language server is recompiling multiple times:

    : Failed to get compile settings for +configname=flex.
    : 
    : Failed to get compile settings for +configname=flex.
    : 
    : Failed to get compile settings for +configname=flex.
    : 
    : Failed to get compile settings for +configname=flex.
    : 
    : Failed to get compile settings for +configname=flex.
    : 
    : Failed to get compile settings for +configname=flex.

Here is an example of the file errors that I am seeing with "git status":

    C:\Flex\workspace\Moonshine-IDE>git status
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/bin-debug/history/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/build/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/html-template/history/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/src/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project (Flex)/src/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project (Flex)/visualeditor-src/': Permission denied
    On branch master
    Your branch is up to date with 'origin/master'.

    nothing to commit, working tree clean

Expected output (this is displayed after Moonshine is closed):

    C:\Flex\workspace\Moonshine-IDE>git status
    On branch master
    Your branch is up to date with 'origin/master'.

    nothing to commit, working tree clean

These errors prevent me from checking out another branch with Git.

@joshtynjala, have you seen a problem like this before?  In theory this could affect the language server with VSCode as well.

@rat-moonshine, my proposed solution is:
1. User tries to checkout a branch (or a similar operation)
2. Moonshine stops the language server(s) associated with that project
3. Moonshine executes the checkout
4. Moonshine restarts the language server

**Comment by JoelProminic** [comment]
I found I could trigger the same problem when deleting a directory within the source directory:

1. Create a new Moonshine project
2. Open the project in the Command Line and run "git init".  I don't think this problem is dependent on Git, but this is an easy way to see the errors.
3. Create a new directory under src:  testdelete
4. Create a new class in src/testdelete:  TestDelete.mxml
5. Verify there are no errors with "git status"
6. Delete src/testdelete
7. "git status" shows:

    C:\Users\JAnderson\Documents\Flex\temp-workspace\TestLocalGit>git status
    warning: could not open directory 'src/testdelete/': Permission denied
    On branch master
    ...

**Comment by JoelProminic** [comment]
@rat-moonshine could not reproduce my "Permission Denied" errors on Windows 7, but he did report that he saw a lot of errors from the language server in his test.

**Comment by joshtynjala** [comment]
I recently saw something similar in VSCode on Windows when I tried to rename a particular folder added to the source-path. I didn't have time to investigate at the time, though.

Regardless, I wonder if the language server isn't the only thing that has files open when you're testing in Moonshine. I say that because the language server shouldn't be trying to read the contents of these folders:

> /bin-debug/history/'
> /build/'
> /html-template/history/

This error could also be relevant to the issue:

> : Failed to get compile settings for +configname=flex.

Your project's SDK doesn't seem to be set up correctly. The Royale compiler that powers the language server seems to be having trouble finding or parsing the *flex-config.xml* file that's inside your project's SDK.

> but he did report that he saw a lot of errors from the language server in his test.

It would be great if @rat-moonshine could share those errors.

**Comment by rat-moonshine** [comment]
I see after a branch switch, language-server reports/throws-exception to the files which were exists in the previous branch but not to the switched branch. Following are my test results. Before beginning of this test I have downloaded a fresh copy of the Moonshine Git to my system. 

(_Note_: for my following tests I choose to use command line instead of Moonshine Git options)

- I ensured I'm on 'master' branch
- Opened MoonshineDESKTOPevolved (MDE) project on Moonshine
- Console thrown language server-error with its `{locale}` path problem (which reported as a separate issue)
- I tried to switch branch from command line - `git checkout features/issue_302_improvement_to_exporting_process_of_primefaces_ve`
- This worked 
- I ran `git status` on command line - eventually Moonshine thrown console errors against the files which were present in currently opened project's file system, but not anymore after the branch switched. These are few of those errors about missing files (after branch change) :

```
: java.io.FileNotFoundException: D:\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\components\popup\GitAuthenticationPopup.mxml
: 	at org.apache.royale.compiler.filespecs.FileSpecification.createReader(FileSpecification.java:79)
: 	at org.apache.royale.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:85)
: 	at org.apache.royale.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:38)
: 	at org.apache.royale.compiler.internal.caches.ConcurrentCacheStoreBase.get(ConcurrentCacheStoreBase.java:69)
: 	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:52)
: 	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:36)
: 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.getMXMLData(MXMLCompilationUnit.java:281)
: 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleFileScopeRequest(MXMLCompilationUnit.java:168)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processFileScopeRequest(CompilationUnitBase.java:863)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$200(CompilationUnitBase.java:108)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:287)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:283)
: 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
: 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
: 	at java.lang.Thread.run(Thread.java:745)
: java.io.FileNotFoundException: D:\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\components\popup\GitCommitSelectionPopup.mxml
: 	at org.apache.royale.compiler.filespecs.FileSpecification.createReader(FileSpecification.java:79)
: 	at org.apache.royale.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:85)
: 	at org.apache.royale.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:38)
: 	at org.apache.royale.compiler.internal.caches.ConcurrentCacheStoreBase.get(ConcurrentCacheStoreBase.java:69)
: 	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:52)
: 	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:36)
: 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.getMXMLData(MXMLCompilationUnit.java:281)
: 
: 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleFileScopeRequest(MXMLCompilationUnit.java:168)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processFileScopeRequest(CompilationUnitBase.java:863)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$200(CompilationUnitBase.java:108)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:287)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:283)
: 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
: 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
: 	at java.lang.Thread.run(Thread.java:745)
: java.io.FileNotFoundException: D:\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\components\popup\GitXCodePermissionPopup.mxml
: 	at org.apache.royale.compiler.filespecs.FileSpecification.createReader(FileSpecification.java:79)
: 	at org.apache.royale.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:85)
: 	at org.apache.royale.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:38)
: 	at org.apache.royale.compiler.internal.caches.ConcurrentCacheStoreBase.get(ConcurrentCacheStoreBase.java:69)
: 	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:52)
: 	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:36)
: 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.getMXMLData(MXMLCompilationUnit.java:281)
: 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleFileScopeRequest(MXMLCompilationUnit.java:168)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processFileScopeRequest(CompilationUnitBase.java:863)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$200(CompilationUnitBase.java:108)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:287)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:283)
: 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
: 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
: 
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
: 	at java.lang.Thread.run(Thread.java:745)
```

@joshtynjala , if this somehow manageable internally with the language-server, like, a flag that can tell the language-server when a Moonshine git process is about to start, and when finish refresh its file list - is that doable? That might help us re-align the updated file systems with opened project's language-server.

@JoelProminic also suggested one option - to close the language-server before such Git process starts from Moonshine, and re-start after the process ends. I'm not sure if this an intuitive way to stop/start the language-server - @joshtynjala please advise if this way has any overhead.

**Comment by rat-moonshine** [comment]
I also able to reproduce "Permission Denied" error inside Moonshine in my tests - following tests ran inside Moonshine involve multiple branch switch occasion - first one from 'master' to 'features/issue_302_improvement_to_exporting_process_of_primefaces_ve' and second one from 'features/issue_302_improvement_to_exporting_process_of_primefaces_ve' to 'master'. 

1. Opened MDE in Moonshine - having current branch 'master'
2. Language server thrown error to console with its `{locale}` path settings
3. Tried to switch branch from Moonshine:

```
: Fetching branch details...
: your branch is up-to-date with 'origin/features/issue_302_improvement_to_exporting_process_of_primefaces_ve'.
: switched to branch 'features/issue_302_improvement_to_exporting_process_of_primefaces_ve'
```

4. I noticed a brief system freeze after the above process completed - not sure what it caused, though
5. Tried to restore 'master' branch from Moonshine:
```
: Fetching branch details...
: error: cannot stat 'ide/moonshinesharedcore/src/actionscripts/plugin/actionscript/as3project/files': permission denied
: error: cannot stat 'ide/moonshinesharedcore/src/actionscripts/plugin/actionscript/as3project/files': permission denied
```
6. Tried to switch to 'master' from command line - same above error
7. Closed Moonshine - terminate the language server Java process by going to Task Manager
8. Tried to switch again through command line - succeed

**Comment by JoelProminic** [comment]
This error seems to be related to #221.  I have reopened the issue:

    : Failed to get compile settings for +configname=flex.


The {locale} error was reported in #313.  Note that if the language server does not shut down automatically, then the files that are locked by the language server (and the corresponding filesystem errors reported in this issue) will not be released until the language server is killed manually:

    : Failed to watch source path: /Users/joelanderson/Documents/Flex/temp_workspace/Moonshine-IDE/ide/MoonshineSharedCore/src/locale/{locale}

@joshtynjala made a good point that these files should not be watched by the language server.  I don't have an an explanation for this for now:

> /bin-debug/history/
> /build/
> /html-template/history/

**Comment by joshtynjala** [comment]
@rat-moonshine I opened the MDE project in Moonshine, and I'm trying to reproduce your steps [here](https://github.com/prominic/Moonshine-IDE/issues/315#issuecomment-400226409). When I try to switch branches using **Github** -> **Switch to Branch**, it fails with the following text in the console:

> : Fetching branch details...
: git@github.com: Permission denied (publickey).
: fatal: Could not read from remote repository.
: Please make sure you have the correct access rights
: and the repository exists.

It may be relevant that I had cloned the repository from the command line already, and I opened one of its projects in Moonshine for the first time. I did not clone the repository from Moonshine's new Github menu.

**Comment by rat-moonshine** [comment]
@joshtynjala were you on Windows or macOS?

**Comment by joshtynjala** [comment]
@rat-moonshine Windows

**Comment by rat-moonshine** [comment]
I cloned a fresh copy of Moonshine-IDE off-Moonshine (with TortoiseGit) into my Windows system. Then I tried again by the steps those I've recorded [here](https://github.com/prominic/Moonshine-IDE/issues/315#issuecomment-400226409). But I couldn't able to reproduce the kind of message, during my tests. 

Furthermore, I'm not clear why it talks about authentication when 'Switch to Branch' only uses 'git checkout' command and which do not involves any auth process.

**Comment by joshtynjala** [comment]
I have committed some new changes to the language server that should make it work better when switching branches with Git. Please give it a try and let me know if any issues can still be reproduced.

**Comment by rat-moonshine** [comment]
With my initial tests on Windows, I see following things:

- Opening MDE project didn't thrown the {locale} error anymore
- Except once, I couldn't able to reproduce the problems described [here](https://github.com/prominic/Moonshine-IDE/issues/315#issuecomment-400190959) and [here](https://github.com/prominic/Moonshine-IDE/issues/315#issuecomment-400226409) - I able to switch between the said two branches effectively without any file-system error, in consecutive tests

I shall keep an eye while testing on macOS if I can able to reproduce the errors or not. However, I see a new error while deleting a project, but this may not be related to the language-server, and I need to investigate. While deleting a project it throws following IO/Error:

```
Error #2044: Unhandled IOErrorEvent:. text=Error #2038: File I/O Error.
	at flash.filesystem::File$/getFile()
	at flash.filesystem::File$/get desktopDirectory()
	at actionScripts.impls::IFileBridgeImp()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\impls\IFileBridgeImp.as:57]
	at actionScripts.factory::FileLocation()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\factory\FileLocation.as:37]
	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\plugins\as3project\importer\FlashDevelopImporter.as:53]
	at actionScripts.plugins.as3project::CreateProject/createFileSystemBeforeSave()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\plugins\as3project\CreateProject.as:822]
	at actionScripts.plugins.as3project::CreateProject/createSave()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\plugins\as3project\CreateProject.as:555]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at mx.core::UIComponent/dispatchEvent()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\core\UIComponent.as:13688]
	at Function/actionScripts.plugin.settings:SettingsView/actionScripts.ui:IContentWindow:save/actionScripts.plugin.settings:goSave()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\SettingsView.mxml:173]
	at actionScripts.plugin.settings::SettingsView/save()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\SettingsView.mxml:163]
	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()[E:\DevareaLocal\Prominic\Prominic_Git\git\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\SettingsView.mxml:463]
```

**Comment by JoelProminic** [comment]
I still get the error on Windows with the latest build from Bamboo:
1. Clone/update the latest version of Moonshine-IDE
2. Checkout the "master" branch
3. Open ide/MoonshineDESKTOPevolved in Moonshine
4. Checkout the Test_Devsena branch using GitHub > Switch to Branch
5. Run "git status" from the command line


    C:\Flex\workspace\Moonshine-IDE\ide>git status
    warning: could not open directory 'ide/MoonshineDESKTOPevolved/src/assets/awaybuilderassets/orientationtool/': Permission denied
    warning: could not open directory 'ide/MoonshineDESKTOPevolved/src/assets/awaybuilderassets/spritetextures/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/actionScripts/plugin/actionscript/as3project/files/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/actionScripts/plugin/core/mouse/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/actionScripts/plugin/errors/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/actionScripts/plugin/projectPanel/events/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/actionScripts/ui/tabNavigator/event/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/actionScripts/ui/tabNavigator/skin/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/components/popup/newFile/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/files/visualeditor/primeFaces/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/PrimeFaces Project/src/main/webapp/WEB-INF/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project/src_flex/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project/src_primeface/main/resources/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project/src_primeface/main/webapp/WEB-INF/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project/visualeditor-src/main/webapp/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/visualEditor/plugin/': Permission denied
    On branch Test_Devsena
    Your branch is up to date with 'origin/Test_Devsena'.

    nothing to commit, working tree clean



I can also see the same error when doing a checkout from the command line:
6. Restart Moonshine - this clears the git status errors
7. From the command line, run "git checkout master"
8. Run "git status" from the command line.  I get these errors:

    C:\Flex\workspace\Moonshine-IDE\ide>git status
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/bin-debug/history/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/build/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/html-template/history/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/src/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project (Flex)/src/': Permission denied
    warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project (Flex)/visualeditor-src/': Permission denied
    On branch master
    Your branch is up to date with 'origin/master'.

    nothing to commit, working tree clean

**Comment by joshtynjala** [comment]
Since I can't seem to switch branches inside Moonshine, I was trying to reproduce this issue from the command line. Unfortunately, even on the command line, I cannot reproduce this issue. I tried doing it in both PowerShell and the legacy cmd.exe, but the **git status** command always worked correctly for me when I had the project open in Moonshine.

**Comment by joshtynjala** [comment]
I feel like this shouldn't matter, but I notice that you have a project in a root directory of the c:\ drive. I'm testing in a directory that is inside my user directory *c:\Users\josht*. I wonder if Windows is being more restrictive with something outside of the user directory...

**Comment by rat-moonshine** [comment]
I tried to re-visit @JoelProminic 's test cases again with latest source, and following was my test results on Windows 10:

1. Clone/update the latest version of Moonshine-IDE
2. Checkout the "master" branch
3. Open ide/MoonshineDESKTOPevolved in Moonshine
4. Checkout the Test_Devsena branch using GitHub > Switch to Branch
5. Run "git status" from the command line
6. This didn't thrown me anymore error on Moonshine console

1. Restart Moonshine - this clears the git status errors
2. From the command line, run "git checkout master"
3. Run "git status" from the command line. 
4. The following permission errors are still valid on Windows:

```
C:\Flex\workspace\Moonshine-IDE\ide>git status
warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/bin-debug/history/': Permission denied
warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/build/': Permission denied
warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/html-template/history/': Permission denied
warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Flex Browser Project (FlexJS, Royale)/src/': Permission denied
warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project (Flex)/src/': Permission denied
warning: could not open directory 'ide/MoonshineSharedCore/src/elements/templates/projects/Visual Editor Project (Flex)/visualeditor-src/': Permission denied
On branch master
Your branch is up to date with 'origin/master'.
```

**Comment by joshtynjala** [comment]
Commit 0c2fba3c89fdf366a37c885ef5d669545a74ee1f fixes the "File or directory is in use" error in #319. The language server was accidentally keeping some files open after reading their contents, but now they are properly closed. This issue may also be fixed. Can someone check?

**Comment by rat-moonshine** [comment]
In my initial tests, while I couldn't able to reproduce anymore the above permission denied errors, which is good, #325 seems still valid. Though, I'm not sure if both the issues are related.

**Comment by joshtynjala** [comment]
I don't think that they are related.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Do you think we can close that one ?

**Comment by rat-moonshine** [comment]
Let's wait till Joel complete his side of testing.

**Comment by JoelProminic** [comment]
I am still consistently getting errors when switching between the "master" and "Test_Devsena" branches:

    C:\Flex\workspace\Moonshine-IDE\ide\MoonshineDESKTOPevolved>git status
    warning: could not open directory 'ide/MoonshineDESKTOPevolved/src/actionScripts/languageServer/': Permission denied
    warning: could not open directory 'ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/git/model/': Permission denied
    warning: could not open directory 'ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/ui/editor/text/': Permission denied
    warning: could not open directory 'ide/MoonshineDESKTOPevolved/src/assets/awaybuilderassets/images/': Permission denied
    warning: could not open directory 'ide/MoonshineDESKTOPevolved/src/assets/awaybuilderassets/orientationtool/': Permission denied
    ...


These errors clear after I close Moonshine.

**Comment by joshtynjala** [comment]
One thing worth mentioning. When you switch branches, it may take some time for the language server to completely parse all of the updated files. Especially if there are many files that are changed as a result of switching branches.

It might be worth trying to wait 30 seconds to a minute before running the git status command. You may find that it starts working correctly after that.

If that doesn't work, I have no idea what could cause this. Especially since I still cannot reproduce on my computer. It might be something that we need to live with for a while until more clues pop up.

**Comment by JoelProminic** [comment]
After first seeing an error from "git status", I left Moonshine open for hours, but the error did not clear.

However, when I switched a branch and then waited for an hour before running "git status", the error did not trigger.  When I waited for only 1-2 minutes, though, I still got the permission denied errors.

My Windows VM has been running a bit slow lately, but this still seems problematic.  Restarting my VM did not change the behavior.

If no one else can reproduce this, then we can put this issue on hold until we have more clues.   I can workaround this by restarting Moonshine, which is inconvenient but not too disruptive.
