### ISSUE TITLE
Add support for Apache Royale

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#50]
Add support for [Apache Royale](http://royale.apache.org/) with backward compatibility to FlexJS.

**Comment by piotrzarzycki21** [comment]
Initial support for Apache Royale has been added. If we open Apache Royale project Moonshine should be able to build it both SWF and JS version. Code completion is not working right now, but it will probably start once @joshtynjala finish BowlerHatLLC/vscode-nextgenas/issues/144

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Do you know if builds of the Royale compiler JARs are being deployed to the Apache Snapshots Maven repo?

**Comment by piotrzarzycki21** [comment]
@joshtynjala compiler and typedefs has been deployed, but with framework itself something is wrong.  I have an assumption it is caused by this [problems](http://apache-royale-development.20373.n8.nabble.com/Maven-Core-module-reporting-errors-td368.html). I didn't look into that yet, but I can if you need those jars in place to move forward.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 I don't need the framework, so that shouldn't be a problem.

**Comment by piotrzarzycki21** [comment]
Just pushed couple of changes related to Apache Royale to conform with latest renaming work in SDK. 
@joshtynjala code completion is working in Moonshine when I'm using last Apache Royale Nightly build!

**Comment by piotrzarzycki21** [comment]
Moonshine after my latest commits now will be able to:
- Open Apache Royale project
- Build project
- Code Intelligence working

**Comment by JoelProminic** [comment]
@piotrzarzycki21, did you want to include this issue in the 1.6.1 issue list?   What is still left to do?

By the way, is there an easy way to install the nightly Apache Royale build?  I tried to use the Apache Flex SDK Installer, but it seemed like the nightly build was still FlexJS.

**Comment by piotrzarzycki21** [comment]
@JoelProminic yes it's included in 1.6.1 I don't see any harm with that. My tests went pretty well with this partial support. Once we release this version I would like to discuss farther how we handle new project creation and it will be all in case of support.
Nightly build and upcoming releases of Royale won't be available through the installer - You will be able to download it directly from the [website](http://royale.codeoscopic.com/download/) (under construction), Node npm and eventually still use Maven.

In the provided links you have basically two links:

- apache-royale-0.9.0... - You can build application to SWF and JS (it may change the name to apache-royale-flexjs-0.9.0 - we probably have for that vote)
- apache-royale-jsonly-0.9.0 - You can build application to JS only - no Flash dependency.

**Comment by piotrzarzycki21** [comment]
I just added option where user will be able to create new Royale project by clicking either on "File" -> "New" or Home screen -> "Flex Browser Project (FlexJS)".

In project creator user gets drop down list with ability to choose type of project template.

**Comment by JoelProminic** [comment]
I created a new Royale project from the template.

Then I tried to run Project > Build & Run with a JS-only Apache Royale SDK.  I got this error:

```
 Compiling TestRoyale
: Using Royale Compiler codebase: /Users/joelanderson/SDKs/apache-royale-jsonly-0.9.0-bin-nightly-2017-12-05/js/bin/../..
: Using Royale SDK: /Users/joelanderson/SDKs/apache-royale-jsonly-0.9.0-bin-nightly-2017-12-05
: MXMLJSC
: +royalelib=/Users/joelanderson/SDKs/apache-royale-jsonly-0.9.0-bin-nightly-2017-12-05/frameworks
: -sdk-js-lib=/Users/joelanderson/SDKs/apache-royale-jsonly-0.9.0-bin-nightly-2017-12-05/frameworks/js/Royale/generated-sources
: -load-config+=obj/TestRoyaleConfig.xml
: -optimize=false
: -debug=true
: -o
: bin-debug/TestRoyale.swf
: -compiler.targets=SWF
: Loading configuration: /Users/joelanderson/SDKs/apache-royale-jsonly-0.9.0-bin-nightly-2017-12-05/frameworks/royale-config.xml
: Loading configuration: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/obj/TestRoyaleConfig.xml
: scanning for overrides: IStrand
: scanning for overrides: Listenable
: scanning for overrides: IDisposable
: scanning for overrides: Disposable
: scanning for overrides: EventTarget
: scanning for overrides: IEventDispatcher
: scanning for overrides: EventDispatcher
: scanning for overrides: HTMLElementWrapper
: scanning for overrides: IFlexInfo
: scanning for overrides: ApplicationBase
: scanning for overrides: IInitialViewApplication
: scanning for overrides: IParent
: scanning for overrides: IPopUpHost
: scanning for overrides: IRenderedObject
: scanning for overrides: Application
: scanning for overrides: TestRoyale
: scanning for overrides: Event
: scanning for overrides: BrowserEvent
: scanning for overrides: ListenableKey
: scanning for overrides: events
: scanning for overrides: IStatesObject
: scanning for overrides: IChild
: scanning for overrides: IUIBase
: scanning for overrides: IApplicationView
: scanning for overrides: IBead
: scanning for overrides: IBeadModel
: scanning for overrides: IValuesImpl
: scanning for overrides: ILayoutChild
: scanning for overrides: IParentIUIBase
: scanning for overrides: IRoyaleElement
: scanning for overrides: IStrandWithModel
: scanning for overrides: IStyleableObject
: scanning for overrides: UIBase
: scanning for overrides: ValuesManager
: scanning for overrides: IMXMLDocument
: scanning for overrides: IContainer
: scanning for overrides: IContentViewHost
: scanning for overrides: ILayoutParent
: scanning for overrides: ILayoutView
: scanning for overrides: GroupBase
: scanning for overrides: ViewBase
: scanning for overrides: View
: scanning for overrides: WrappedHTMLElement
: scanning for overrides: EventUtils
: scanning for overrides: KeyboardEventConverter
: scanning for overrides: MouseEventConverter
: scanning for overrides: IBrowserEvent
: scanning for overrides: BrowserEvent
: scanning for overrides: ElementEvents
: scanning for overrides: IRoyaleEvent
: scanning for overrides: Event
: scanning for overrides: ValueChangeEvent
: scanning for overrides: IStrandPrivate
: scanning for overrides: ContainerBase
: scanning for overrides: Container
: scanning for overrides: Label
: scanning for overrides: CSSUtils
: scanning for overrides: MXMLDataInterpreter
: scanning for overrides: Timer
: scanning for overrides: ICSSImpl
: scanning for overrides: SimpleCSSValuesImpl
: scanning for overrides: MouseButton
: scanning for overrides: ContainerBaseStrandChildren
: scanning for overrides: IBeadController
: scanning for overrides: IBeadLayout
: scanning for overrides: IBeadView
: scanning for overrides: IDocument
: scanning for overrides: ILayoutHost
: scanning for overrides: IMeasurementBead
: scanning for overrides: IStatesImpl
: scanning for overrides: KeyConverter
: scanning for overrides: KeyboardEvent
: scanning for overrides: MouseEvent
: scanning for overrides: State
: scanning for overrides: OSUtils
: scanning for overrides: StringPadder
: scanning for overrides: StringUtil
: scanning for overrides: Point
: scanning for overrides: PointUtils
: scanning for overrides: StringTrimmer
: scanning for overrides: BeadViewBase
: scanning for overrides: IContentView
: scanning for overrides: ITextModel
: scanning for overrides: IViewport
: scanning for overrides: IViewportModel
: scanning for overrides: LayoutBase
: scanning for overrides: Rectangle
: scanning for overrides: Size
: scanning for overrides: BasicLayout
: scanning for overrides: HorizontalFlexLayout
: scanning for overrides: HorizontalLayout
: scanning for overrides: TextModel
: scanning for overrides: ViewportModel
: scanning for overrides: GroupView
: scanning for overrides: ContainerView
: scanning for overrides: ContainerContentArea
: scanning for overrides: Viewport
: scanning for overrides: ScrollingViewport
: 2.667378063 seconds
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(671): col: 21 Error: org.apache.royale.html.beads.SolidBackgroundBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(671): col: 21 Error: org.apache.royale.html.beads.SolidBackgroundBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(672): col: 17 Error: org.apache.royale.html.beads.SingleLineBorderBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(672): col: 17 Error: org.apache.royale.html.beads.SingleLineBorderBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(769): col: 15 Error: org.apache.royale.html.beads.TextFieldView is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(769): col: 15 Error: org.apache.royale.html.beads.TextFieldView is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(770): col: 22 Error: org.apache.royale.html.beads.TextFieldLabelMeasurementBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(770): col: 22 Error: org.apache.royale.html.beads.TextFieldLabelMeasurementBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(813): col: 3 Error: 'VScrollBar' is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(813): col: 3 Error: 'VScrollBar' is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(821): col: 3 Error: 'HScrollBar' is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(821): col: 3 Error: 'HScrollBar' is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(933): col: 21 Error: org.apache.royale.html.beads.SolidBackgroundBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(933): col: 21 Error: org.apache.royale.html.beads.SolidBackgroundBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(934): col: 17 Error: org.apache.royale.html.beads.SingleLineBorderBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(934): col: 17 Error: org.apache.royale.html.beads.SingleLineBorderBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(671): col: 21 Error: org.apache.royale.html.beads.SolidBackgroundBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(671): col: 21 Error: org.apache.royale.html.beads.SolidBackgroundBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(672): col: 17 Error: org.apache.royale.html.beads.SingleLineBorderBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(672): col: 17 Error: org.apache.royale.html.beads.SingleLineBorderBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(769): col: 15 Error: org.apache.royale.html.beads.TextFieldView is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(769): col: 15 Error: org.apache.royale.html.beads.TextFieldView is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(770): col: 22 Error: org.apache.royale.html.beads.TextFieldLabelMeasurementBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(770): col: 22 Error: org.apache.royale.html.beads.TextFieldLabelMeasurementBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(813): col: 3 Error: 'VScrollBar' is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(813): col: 3 Error: 'VScrollBar' is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(821): col: 3 Error: 'HScrollBar' is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(821): col: 3 Error: 'HScrollBar' is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(933): col: 21 Error: org.apache.royale.html.beads.SolidBackgroundBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(933): col: 21 Error: org.apache.royale.html.beads.SolidBackgroundBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(934): col: 17 Error: org.apache.royale.html.beads.SingleLineBorderBead is not defined.
: /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale/BasicJS.swc:defaults.css(934): col: 17 Error: org.apache.royale.html.beads.SingleLineBorderBead is not defined.
```

If the plan is to release both normal and JS-only versions of Royale, then we should add some logic that can detect whether the SDK is JS-only and give a clear error like:

    This SDK only supports JavaScript Builds.

I'm open to other solutions for this situation, but I'd like to have something better than the long list of errors shown currently.

Otherwise, the Royale project templates seem to work well with the normal and JS-only nightly builds of Royale.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I will investigate whether I will be able to do this for the next release.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I was able to figure out and recognize whether user is using JS only SDK. I'm displaying message in the console.

I think we should raise feature issue to work on colorize messages in the console.

**Comment by JoelProminic** [comment]
This worked fine for me.  The JSOnly SDK worked with Build & Run as Javascript only, and the normal SDK worked with both Build & Run and Build & Run as Javascript

On a related note, the normal and JSOnly SDKs look identical in the SDK list.  Could we use the same JSOnly detection logic to add a flag in the SDK list (i.e. "Apache Royale 0.9.0 FP11.7 AIR14.0 en_US (JSOnly)")?  As I remember, the SDK label is pulled from the flex-sdk-description.xml currently, so this would be a slight modification to the logic.

Colorized messages on the console sound like a good idea to me - they could also be used to help distinguish between warnings and errors in the compiler output.

**Comment by piotrzarzycki21** [comment]
This is good idea distinguish labels SDK. I will use the method to display this one.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I just pushed changes where I'm adding "JSOnly" to the label. I didn't want to make some extensive changes, so my solution is a bit limited.
- User will have "JSOnly" label in the window "Select SDK"
- User won't have that label here (screenshot below) if he had JSOnly sdk on the list. He will have to select remove it and select it again. In the other words it won't be backward compatible. I will have to make much more changes, which I prefer not to do.
![image](https://user-images.githubusercontent.com/24554795/34437458-a3c57bce-ec9e-11e7-9869-2dd048ad20da.png)

I'm thinking on proposing on Royale dev list changes of the description for JSOnly. We will then remove above solution.

**Comment by JoelProminic** [comment]
I confirmed that I had to remove and re-add the JSOnly SDK from the SDK list in order for the label to display properly in the Custom SDK value.  I'm not too worried about backwards compatibility, since this will be resolved the next time the user adds a new version of the SDK.

By default, the JSOnly label is not visible in the SDK list.  The discription is cut off for all of the SDKs, so we may want to make the Description column and reduce the space for the path.  The isn't very helpful for the Bundled SDKs in my screenshot, anyway:
![image](https://user-images.githubusercontent.com/24532731/34443587-c844de60-ec8d-11e7-844a-b5fbd08063d3.png)

If I expand the column, I noticed that the "(JSOnly)" label is duplicated in the SDK list:
![image](https://user-images.githubusercontent.com/24532731/34443595-d128b7ae-ec8d-11e7-86b0-6d16f2249b5a.png)

**Comment by piotrzarzycki21** [comment]
I just fixed this duplication issue and made some adjustment to columns. It  should be better.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have started initial [discussion](http://apache-royale-development.20373.n8.nabble.com/Distinguish-description-in-quot-royale-sdk-description-xml-quot-between-asjs-and-JSOnly-td1371.html) on the Royale dev list about SDK description. If everything goes ok I will try to fix part with JS inside SDK.

**Comment by JoelProminic** [comment]
I confirmed the duplication issue is resolved.

The SDK list now looks like this:
![image](https://user-images.githubusercontent.com/24532731/34535155-bc6a5b90-f086-11e7-86d3-a533449beb34.png)

Note that the "Bundled" column is no longer visible - was this intentional?

I still don't see "(JSOnly)" with this column width.   Is it visible on your workstation?  If so, I'm wondering what is different.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have started discussion about that on the Dev Royale list. We have end up that we will change royale-sdk-description to the format which brings information about type of SDK. 

```
<royale-sdk-description>
<name>Apache Royale</name>
<version>0.9.0</version>
<build>20180103</build>
        
<output-targets>
    <output-target name="js" version="Ecma5Strict" />
    <output-target name="swf" version="AS3" AIR="14.0" Flash="11.7" />
</output-targets>
</royale-sdk-description>
```

I did changes on SDK sight and in Moonshine. I haven't reported it yet here, cause I still have one small issue on SDK sight. In the results of those changes we will have following name in Moonshine:

![image](https://user-images.githubusercontent.com/24554795/34538182-b4bb7498-f0cb-11e7-93cd-d562b7de26a9.png)

I can display in the JS-only version as you said - currently I'm displaying what we have in output-target name tag. Let me know if you wanted me to change.

Additionally we have new build server much faster, so you can grab [(swf, js)](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/) version and [(js)](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/) - only from there in order to see those changes.

**Comment by piotrzarzycki21** [comment]
As for the Bundle column name I will definitely have to look into that!

**Comment by piotrzarzycki21** [comment]
@JoelProminic I think I have fixed problem with column. Take a look once you get a chance.

**Comment by JoelProminic** [comment]
The Bundled column is still not visible by default:
![image](https://user-images.githubusercontent.com/24532731/34587987-4cbd6b08-f170-11e7-8be2-9daa4ada7b3d.png)

I can see it if I expand the SDK window, though:
![image](https://user-images.githubusercontent.com/24532731/34588005-5e3f298e-f170-11e7-8591-0872e1d67895.png)

**Comment by JoelProminic** [comment]
@piotrzarzycki21, I copied the latest SDKs, and I got similar results to your screenshot.

I noticed that the first link you gave had download links for both the normal and jsonly SDKs, though.  Is there a difference between the jsonly downloads on this page and the and the downloads from the second link?

**Comment by piotrzarzycki21** [comment]
Great question. :) Till yesterdays evening my time there were difference, because build JS only simply contains one issue with royale-sdk-descriptor, but I was able to fix it on the SDK sight.

Currently there is no difference from the user point of view. Difference is only to the way how build is done.

**Build royale-asjs JOB:**
It has setup as an environment variable playerglobal and AIR_HOME - which is simply sign to make swf, js package. Additionally this job once finish whole build is launching special target which is copying only files which allow to create js-only package in that JOB. In the results you are seeing both packages.

**Build royale-asjs_jsonly JOB:**
It doesn't have environment variable playerglobal and AIR_HOME set. It means that process of building automatically create JS only package without launching other swf builds related.

If some day you would like to build on your own SDK by ANT that's the mixture of how to make packages "swf, js" or "js" - only.

Maven build doesn't have such distinguish. Always building both.
