### ISSUE TITLE
Error on Edit > Go To Definition 

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#580]
I see this behavior:
1. Create a new Java Gradle Project
2. Wait for the language server to start
3. Add a new static class variable to the main class, and update that variable in the main method.
4. CMD-Click the reference in main.   The cursor position correctly changes to the definition
5. Select the reference in main, and choose Edit > Go To Definition.  This fails with the error below

    : Error #1034
    : TypeError: Error #1034
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
    : 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
    : 	at actionScripts.ui.menu::MenuPlugin/redispatch()
    :
    : Click here to Report a Bug

Example code:
```
public class TestJavaGradleReference
{
	public static String foo = "bar";
	public static void main(String args[])
	{
	    System.out.println("Hello World!");
		foo = "test";
	}
}
```

Here is an example project (also used for #579):
[2019_06_10__TestJavaGradleReference.zip](https://github.com/prominic/Moonshine-IDE/files/3274089/2019_06_10__TestJavaGradleReference.zip)

**Comment by rat-moonshine** [comment]
Since the trailing-space selection issue fixed in #576 , I could not able to reproduce this again. Can you please check if this still fails elsewhere (?)

**Comment by JoelProminic** [comment]
Testing on macOS with the latest build, I still get the 1034 error for Edit > Go To Definition, regardless of whether I have selected the word or not.

**Comment by piotrzarzycki21** [comment]
I have pushed some fix in that area - it is possible that this was fixed. Try to test if find time.

**Comment by JoelProminic** [comment]
I retried the original test procedure, and I still get this same error (three times) when I try Edit > Go To Definition:

    : Error #1034
    : TypeError: Error #1034
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
    : 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
    : 	at actionScripts.ui.menu::MenuPlugin/redispatch()
    :
    : Click here to Report a Bug

**Comment by JoelProminic** [comment]
@rat-moonshine, please review this to see if you can fix it for tomorrow.  If we can't fix it easily, we can bump it to the next release.

**Comment by rat-moonshine** [comment]
I confirm I able to produce the error on macOS run. This should be fixed now, please, check.

**Comment by JoelProminic** [comment]
Both "Go To Definition" and "Go To Type Definition" work for me now on macOS.
