### ISSUE TITLE
Git / Manage Repositories doesn't work

### ISSUE THREAD

**Issue by Nisaba** [prominic/Moonshine-IDE#613]
Hi,

When I click on Git / Repositories, it displays Settings / Subversion screen.
(maybe a bug)

So, I can't add a new Git repository.

Thank you for your help

**Comment by Nisaba** [comment]
Please note I use 2.4.0 version

**Comment by piotrzarzycki21** [comment]
@Nisaba are you saying that you don't see following options in menu ? 
![moon](https://user-images.githubusercontent.com/24554795/63270087-bf7cfb00-c297-11e9-90b2-794ed1cf38a2.png)

**Comment by Nisaba** [comment]
Yes, I can't reach this screen.
Git / Manage Repositories goes to Settings / Subversion screen

**Comment by piotrzarzycki21** [comment]
Can you show me Help -> About ? - it looks like you have older version of Moonshine, which is pretty weird.

**Comment by Nisaba** [comment]
![image](https://user-images.githubusercontent.com/34550856/63273121-e3870f00-c28c-11e9-96aa-77a785769356.png)

![image](https://user-images.githubusercontent.com/34550856/63273246-21843300-c28d-11e9-8d2c-706ae0a6304c.png)

**Comment by piotrzarzycki21** [comment]
This is a bug. Now I understand. One workaround is to just download SVN using menu **Help** -> **Getting Started** tab - it will setup path in that settings and allows you to use Git.

**Comment by rat-moonshine** [comment]
I have updated the code to open correct sections in Settings when Git or SVN path is not available, or does-not exists after clicking on 'Manage Repositories'. Generally you suppose to get hit by the following screen during startup unless you chose to 'Do not show again' option previously. 

![image](https://user-images.githubusercontent.com/34550856/63273246-21843300-c28d-11e9-8d2c-706ae0a6304c.png)

**Comment by JoelProminic** [comment]
Testing on macOS with the latest 2.5.0 development build, I still can't open Git > Manage Respositories without setting a path for SVN.
1. Open Moonshine
1. Moonshine > Settings
1. Open Subversion tab, clear the value, and save
1. Check the Git tab in the Settings, and confirm that Git Binary is still set
1. Git > Manage Repositories (note that this this is enabled in my test)
1. BUG:  the user is prompted to allow access to XCode.  (Note that I am using the non-Sandbox build, so "Allow Access" doesn't really make sense).
![image](https://user-images.githubusercontent.com/24532731/68512561-62616780-023e-11ea-8b1d-84957658a0a3.png)

However, if the user installs Xcode or Command Line Utils, they should have access to both svn and git, so this probably doesn't matter.

**Comment by JoelProminic** [comment]
On Windows, I see this behavior:
1. Open Moonshine
1. Moonshine > Settings
1. Open Subversion tab, clear the value, and save
1. Check the Git tab in the Settings, and confirm that Git Binary is still set
1. Git > Manage Repositories (note that this this is enabled in my test)
1. BUG:  The Git settings page opens, and I can see the Git Binary is still set

I can repeat the same issue for Subversion > Manage Repositories is the Subversion binary is defined but not Git.

**Comment by rat-moonshine** [comment]
> On Windows, I see this behavior:

This part of the behaviour is suppose to be fixed now. However, an Windows' test is pending.

> Testing on macOS with the latest 2.5.0 development build, I still can't open Git > Manage Respositories without setting a path for SVN.

This is true that XCode or Command Line path uses against both Git and SVN. Thus, having XCode permission once given, that should be re-use later on when needed. I made some changes therefore to match the following order (NOTE: this will not work until a fresh permission given for XCode, as the XCode path now stores to application-data through the permission window) :

1. Open Moonshine
2. Moonshine > Settings
3. Open Subversion tab, clear the value, and save
4. Check the Git tab in the Settings, and confirm that Git Binary is still set
5. Git > Manage Repositories (note that this this is enabled in my test)
6. Manage Repositories window opens properly
7. SVN > Manage Repositories
8. Manage Repositories window opens properly

Since the root-application is common for Git and SVN on macOS, if the permission once given to access it, Moonshine now re-updates the missing SVN or Git path on macOS once 'Git > Manage Repositories' or 'Git > Grant Permission' option clicked. 

If one want to set any custom path instead (against Git or SVN), s/he can do that by opening the respective Settings and by setting the path. If path will found blank and permission to XCode/Command-line once given, that will be re-use.

**Comment by JoelProminic** [comment]
Now on Windows I see this behavior:
1. Open Moonshine
1. Moonshine > Settings
1. Open Subversion tab, clear the value, and save
1. Check the Git tab in the Settings, and confirm that Git Binary is still set
1. Git > Manage Repositories (note that this this is enabled in my test)
1. BUG:  Nothing happens.  I waited a minute to check if Moonshine was just slow, but the Manage Repositories interface did not open.
1. Subversion > Manage Repositories
1. Subversion settings pages opens

**Comment by rat-moonshine** [comment]
The above problem should be fixed now. Please, check.

**Comment by JoelProminic** [comment]
I confirmed that I can open Manage Repositories for Git and Subversion even if the other is not installed now.

I also did a quick test to make sure that I can do a git clone or svn checkout while the other application is not configured.  This also worked fine.
